### ISSUE TITLE
Docker status

### ISSUE THREAD

**Issue by robbiet480** [robotastic/trunk-recorder#365]
Hi @robotastic,

Thought I should create a issue to continue work from https://github.com/robotastic/docker-gnuradio/issues/2. Now that I've figured out the path to get multiple architectures building properly, i'm working on improving the entire `trunk-recorder` Docker ecosystem. This includes updating the two repos `Dockerfile` to follow best practices, slimming them down as much as possible and improving the Docker Compose story. Unrelated to `trunk-recorder` specifically, I'm also working on containerizing @chuot's `rdio-scanner` so that users can get a whole stack running with a single Docker Compose file and much faster too, especially for those on Raspberry Pi. 

I've created this issue because I was hoping to get the current lay of the land from you and @EricTendian. I see a lot of Docker issues in multiple repos but am unsure where my time is best spent so as to not duplicate work. So, a few questions to start:

1. Based on #349 it appears we need a new Dockerfile to support GNURadio 3.8. Is this correct? I see https://github.com/robotastic/trunk-recorder-docker-gr3.8, is this actually working? Should we start using GNURadio 3.8 as the base for Docker?
2. What's the issue with Locales? I see you are setting everything to `en_US.UTF-8`. Why? Can we stop doing that and just use `C` or `C.UTF-8`?
3. Is there any way to build a static binary so that we can just have the GNURadio and other deps from `docker-gnuradio` and none of the extra cruft of this repo? I like keeping Docker images nice and small so its quick for users to get going.
4. Are there any magic cmake or make flags I can set to optimize cross compiling? As mentioned in https://github.com/robotastic/docker-gnuradio/issues/2 compile times are quite long right now. I'd like to speed those up if possible.

Here's the current Dockerfile I'm using which works nicely and hews to expected Docker standards:

```Dockerfile
FROM robotastic/docker-gnuradio:latest

WORKDIR /src

COPY . .

RUN cmake . && make -j`nproc` && cp recorder /recorder

CMD ["/recorder"]
```

And the new and improved `docker-compose.yaml`, featuring `rdio-scanner` support too:

```yaml
version: '3'
volumes:
  rdio_database:
services:
  recorder:
    image: robotastic/trunk-recorder:latest
    container_name: trunk-recorder
    restart: always
    devices:
      - /dev/bus/usb/001/003:/dev/bus/usb/001/003
    volumes:
      - ./media:/app/media
      - ./config:/app/config
      - ./ebrcs.csv:/app/ebrcs.csv
  rdio:
    image: robbiet480/rdio-scanner:latest
    container_name: rdio-scanner
    volumes:
      - ./rdio_config.json:/app/server/config.json
      - rdio_database:/app/server/database.sqlite
      - ./media:/calls
```

The big improvements to the Compose file are no more having to build a second image just for Compose, not having to run privileged mode and explicitly mounting CSVs instead of just copying everything over.

Once Docker is improved I strongly recommend that you suggest it as the premiere installation method for end users, especially those on Raspberry Pi, so that they don't have to deal with deps and compile times.

Excited to hear your thoughts and contribute to this fantastic project!
