### ISSUE TITLE
Airspy Broken on Docker Container After Changes for Multiple Airspy Dongles

### ISSUE THREAD

**Issue by HarrisonWilson** [robotastic/trunk-recorder#737]
With the changes in 4.4.1 (and 4.4.2), my Airspy stopped working. Rolling back to the 4.4.0 image works fine.

It looks like it detects the correct AirSpy, but won't load it and goes into infinite boot loop.

The error(s) received are:
`Attempting to open airspy by s/n= 0x00007FB8CA605AD0`
`[2022-11-29 14:38:35.839918] (error)   Failed parsing Config: Failed to open AirSpy device (-5) AIRSPY_ERROR_NOT_FOUND`

Here is the compose file for reference
```yaml
  recorder:
    image: robotastic/trunk-recorder:4.4.2
    container_name: recorder
    user: root:root
    restart: always
    devices:
      - '/dev/bus/usb'
    volumes:
      - "/opt/recorder/config.json:/app/config.json"
      - type: tmpfs 
        target: /recordings
        tmpfs:
          size: 1000000000
```
